"""Feature configuration shared by training and inference."""

from __future__ import annotations

MODEL_VERSION = "v1.0.0"

# Raw columns loaded from application_train.csv for training
RAW_COLUMNS = [
    "TARGET",
    "NAME_CONTRACT_TYPE",
    "CODE_GENDER",
    "FLAG_OWN_CAR",
    "FLAG_OWN_REALTY",
    "CNT_CHILDREN",
    "AMT_INCOME_TOTAL",
    "AMT_CREDIT",
    "AMT_ANNUITY",
    "AMT_GOODS_PRICE",
    "NAME_TYPE_SUITE",
    "NAME_INCOME_TYPE",
    "NAME_EDUCATION_TYPE",
    "NAME_FAMILY_STATUS",
    "NAME_HOUSING_TYPE",
    "DAYS_BIRTH",
    "DAYS_EMPLOYED",
    "OWN_CAR_AGE",
    "OCCUPATION_TYPE",
    "CNT_FAM_MEMBERS",
    "ORGANIZATION_TYPE",
    "REGION_RATING_CLIENT",
    "FLAG_EMAIL",
    "FLAG_PHONE",
    "FLAG_WORK_PHONE",
    "WEEKDAY_APPR_PROCESS_START",
]

CATEGORICAL_FEATURES = [
    "NAME_CONTRACT_TYPE",
    "CODE_GENDER",
    "FLAG_OWN_CAR",
    "FLAG_OWN_REALTY",
    "NAME_TYPE_SUITE",
    "NAME_INCOME_TYPE",
    "NAME_EDUCATION_TYPE",
    "NAME_FAMILY_STATUS",
    "NAME_HOUSING_TYPE",
    "OCCUPATION_TYPE",
    "ORGANIZATION_TYPE",
    "WEEKDAY_APPR_PROCESS_START",
]

NUMERIC_FEATURES = [
    "CNT_CHILDREN",
    "AMT_INCOME_TOTAL",
    "AMT_CREDIT",
    "AMT_ANNUITY",
    "AMT_GOODS_PRICE",
    "AGE_YEARS",
    "EMPLOYMENT_YEARS",
    "OWN_CAR_AGE",
    "CNT_FAM_MEMBERS",
    "REGION_RATING_CLIENT",
    "FLAG_EMAIL",
    "FLAG_PHONE",
    "FLAG_WORK_PHONE",
    "CREDIT_INCOME_RATIO",
    "ANNUITY_INCOME_RATIO",
    "CREDIT_GOODS_RATIO",
]

FEATURE_COLUMNS = NUMERIC_FEATURES + CATEGORICAL_FEATURES

# Form dropdown options (aligned with training data, excluding rare/invalid)
FORM_OPTIONS = {
    "NAME_CONTRACT_TYPE": ["Cash loans", "Revolving loans"],
    "CODE_GENDER": ["F", "M"],
    "FLAG_OWN_CAR": ["N", "Y"],
    "FLAG_OWN_REALTY": ["N", "Y"],
    "NAME_TYPE_SUITE": [
        "Unaccompanied",
        "Family",
        "Spouse, partner",
        "Children",
        "Other_A",
        "Other_B",
        "Group of people",
    ],
    "NAME_INCOME_TYPE": [
        "Working",
        "Commercial associate",
        "Pensioner",
        "State servant",
        "Unemployed",
        "Student",
        "Businessman",
        "Maternity leave",
    ],
    "NAME_EDUCATION_TYPE": [
        "Secondary / secondary special",
        "Higher education",
        "Incomplete higher",
        "Lower secondary",
        "Academic degree",
    ],
    "NAME_FAMILY_STATUS": [
        "Married",
        "Single / not married",
        "Civil marriage",
        "Separated",
        "Widow",
    ],
    "NAME_HOUSING_TYPE": [
        "House / apartment",
        "With parents",
        "Municipal apartment",
        "Rented apartment",
        "Office apartment",
        "Co-op apartment",
    ],
    "OCCUPATION_TYPE": [
        "Laborers",
        "Sales staff",
        "Core staff",
        "Managers",
        "Drivers",
        "High skill tech staff",
        "Accountants",
        "Medicine staff",
        "Security staff",
        "Cooking staff",
        "Cleaning staff",
        "Private service staff",
        "Low-skill Laborers",
        "Waiters/barmen staff",
        "Secretaries",
        "Realty agents",
        "HR staff",
        "IT staff",
    ],
    "ORGANIZATION_TYPE": [
        "Business Entity Type 3",
        "XNA",
        "Self-employed",
        "Other",
        "Medicine",
        "Business Entity Type 2",
        "Government",
        "School",
        "Trade: type 7",
        "Kindergarten",
        "Construction",
        "Business Entity Type 1",
        "Transport: type 4",
        "Trade: type 3",
        "Industry: type 9",
        "Industry: type 3",
        "Security Ministries",
        "Transport: type 2",
        "Postal",
        "Agriculture",
        "Police",
        "Military",
        "Bank",
        "Hotel",
        "Services",
        "Industry: type 11",
        "Transport: type 3",
        "Industry: type 7",
        "Electricity",
        "Industry: type 4",
        "Trade: type 2",
        "University",
        "Insurance",
        "Restaurant",
        "Housing",
        "Industry: type 1",
        "Advertising",
        "Trade: type 6",
        "Mobile",
        "Legal Services",
        "Security",
        "Telecom",
        "Industry: type 5",
        "Emergency",
        "Industry: type 2",
        "Realtor",
        "Culture",
        "Industry: type 12",
        "Trade: type 1",
        "Transport: type 1",
        "Industry: type 6",
        "Industry: type 10",
        "Religion",
        "Industry: type 13",
        "Trade: type 4",
        "Trade: type 5",
        "Industry: type 8",
        "Cleaning",
    ],
    "WEEKDAY_APPR_PROCESS_START": [
        "MONDAY",
        "TUESDAY",
        "WEDNESDAY",
        "THURSDAY",
        "FRIDAY",
        "SATURDAY",
        "SUNDAY",
    ],
    "REGION_RATING_CLIENT": [1, 2, 3],
}

DEFAULT_APPROVAL_THRESHOLD = 0.15
RISK_LEVELS = {
    "Low": (0.0, 0.08),
    "Medium": (0.08, 0.15),
    "High": (0.15, 1.01),
}
